services:
  # Backend Laravel API
  - type: web
    name: taskwise-backend
    env: docker
    region: frankfurt
    plan: starter
    buildCommand: |
      chmod +x deploy.sh
      ./deploy.sh
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: APP_NAME
        value: TaskWise
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: 5432
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: redis
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: SESSION_LIFETIME
        value: 120
      - key: DB_HOST
        fromDatabase:
          name: taskwise-database
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: taskwise-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: taskwise-database
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: taskwise-database
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: taskwise-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: taskwise-redis
          property: port

  # Frontend React SPA
  - type: web
    name: taskwise-frontend
    env: static
    region: frankfurt
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://taskwise-backend.onrender.com/api
      - key: VITE_APP_ENV
        value: production

databases:
  # PostgreSQL Database
  - name: taskwise-database
    databaseName: taskwise_production
    user: taskwise_user
    plan: starter
    region: frankfurt

services:
  # Redis Cache
  - type: redis
    name: taskwise-redis
    plan: starter
    region: frankfurt
    maxmemoryPolicy: allkeys-lru 